author: "Big Nerd Ranch"
author_url: "http://bignerdranch.github.io"
copyright: "© 2014-2016 [Big Nerd Ranch](//www.bignerdranch.com) under [MIT license](https://raw.githubusercontent.com/bignerdranch/CoreDataStack/master/LICENSE)."
custom_categories:
  - name: Type Safe Monitors
    children:
    - EntityMonitor
    - EntityMonitorDelegate
    - FetchedResultsController
    - FetchedResultsControllerDelegate
  - name: Extensions
    children:
    - NSFetchRequestResult
    - NSManagedObjectContext
    - NSPersistentStoreCoordinator
    - Bundle
  - name: Supporting Structs and Enums
    children:
    - FetchedResultsObjectChange
    - FetchedResultsSectionChange
    - FetchedResultsSectionInfo
    - FireFrequency
  - name: Deprecated
    children:
    - CoreDataStack
    - CoreDataModelable
    - Error
github_url: "https://github.com/bignerdranch/CoreDataStack"
head: |
  <meta property="og:site_name" content="Core Data Stack Programming Guide">
  <meta property="og:description" content="The BNR Core Data Stack is a small framework, written in Swift, that makes it easy to quickly set up a multi-threading ready Core Data stack.">
  <meta property="og:image" content="//www.bignerdranch.com/img/bnr-logo-square.png">
  <link rel="shortcut icon" type="image/x-icon" href="//www.bignerdranch.com/favicon.png">
hide_documentation_coverage: false
skip_undocumented: false
module: CoreDataStack
module_version: "2.0.0"
root_url: "http://bignerdranch.github.io/CoreDataStack/"
theme: fullwidth