# Opt out of sending usage stats
opt_out_usage

#######################################################################
# Project specific variables
#######################################################################

PROJECT_FILE = "CoreDataStack.xcodeproj"

TVOS_SCHEME = "CoreDataStackTV"
MACOS_SCHEME = "CoreDataStackOSX"
IOS_SCHEME = "CoreDataStack"

# We always want to run on the latest version of iOS installed 
# so we're grabbing the highest device by name i.e. iPhone 6s > iPhone 4
LATEST_IPHONE_DEVICE = FastlaneCore::Simulator.all.map { |d| d.name }.select { |s| s[/(iPhone \d.*)/] }.sort.last

#######################################################################
# Lifecycle Hooks
#######################################################################
  
before_all do
end

after_all do |lane|
    # This block is called, only if the executed lane was successful
end

error do |lane, exception|
end

#######################################################################
# Test Lanes
#######################################################################

desc "Runs all the tests"
lane :test do
    # iOS
    scan(scheme: IOS_SCHEME, 
        project: PROJECT_FILE,
        destination: "platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus", 
        clean: true)

    # macOS
    scan(scheme: MACOS_SCHEME, 
        project: PROJECT_FILE, 
        clean: true,
        destination: "platform=macOS,arch=x86_64")

    # tvOS
    scan(scheme: TVOS_SCHEME, 
        project: PROJECT_FILE,
        destination: "platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p",
        clean: true)
end
